development:
  adapter: postgresql
  encoding: unicode
  database: bartorville_development
  pool: 5
  host: localhost
  username: postgres
  password: 08820


production:
  adapter: postgresql
  encoding: unicode
  database: bartorville_production
  pool: 5
  host: localhost
  username: postgres
  password: 08820

