development:
  adapter: postgresql
  encoding: unicode
  database: barter_development
  pool: 5
  host: localhost
  username: postgres
  password: Akarnani1


production:
  adapter: postgresql
  encoding: unicode
  database: barter_production
  pool: 5
  host: localhost
  username: postgres
  password: Akarnani1